siteName: "OpenCilk"
siteDescription: 'The language of performance engineering.'
lang: 'en'
locale: 'en_us'
authorName: 'Bruce Hoppe'
authorURL: 'bruce-hoppe'
authorEmail: 'behoppe@mit.edu'
twitterSite: '@behoppe'
twitterCreator: '@behoppe'